-- AlterTable
ALTER TABLE `transactions` MODIFY `tanggal_entry` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `tanggal_update` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `perintah` VARCHAR(255) NULL,
    MODIFY `sn` TEXT NULL;
